### ISSUE TITLE
Implement a sample Angular app #Hacktoberfest

### ISSUE THREAD

**Issue by isurusndr** [99xt/advanced-react-native-webview#3]
Implement an example anugular app which can be wrapped inside advanced-react-native-webview

**Comment by NsdHSO** [comment]
@isurusndr  I want to take this ticket, how to get this ?

**Comment by lakshin** [comment]
Hi @NsdHSO thank you for your interest in the repository. However I would like to point out that this advanced react native webview which was implemented some time back when the official react native web view lacked functionalities such as file download support. Now the functionalities implemented in this repo are available in the official version of the react native webview.
